name: 🚀 Post Random Repo to Hacker News

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install --with-deps

      - name: Post to Hacker News
        env:
          GITHUB_USERNAME: soodoku                          # ← change as needed
          GITHUB_ORGS: appeler,recite,gojiplus,themains,in-rolls,outside-edge,matmulai              # ← comma-separated orgs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HN_USER_COOKIE: ${{ secrets.HN_USER_COOKIE }}
        run: python post_to_hn.py
